### ISSUE TITLE
Not skipping .gitignore directories.

### ISSUE THREAD

**Issue by raunak51299** [fargusplumdoodle/dump_dir#2]
I have /node_modules in my project and the script is supposed to respect it but it is not.

**Comment by fargusplumdoodle** [comment]
Hey raunak!

Could you provide me the version of `dump_dir`?  This is the latest version

```bash
dump_dir --version
dump_dir version: 1.0.3
commit: a83002a492c6ca878bab59b4ce0fbcbafb4b139a
built at: 2024-07-19T21:59:04Z
```

**Comment by raunak51299** [comment]
Sure, 
```
dump_dir version: 1.0.3
commit: a83002a492c6ca878bab59b4ce0fbcbafb4b139a
built at: 2024-07-19T21:59:04Z
```

**Comment by raunak51299** [comment]
My bad, it was an issue on my end, I was running ` dump_dir any .\api\ ` from parent directory instead of going in the directory and running `dump_dir any .`

**Comment by fargusplumdoodle** [comment]
Thanks for your feedback regardless, I hope this tool is useful for you.

**Comment by raunak51299** [comment]
Yup, thanks for making this tool. It has become essential part of my daily workflow.

**Comment by fargusplumdoodle** [comment]
Eyyyyy incredible!

Well if you have any feature requests I am certainly open to making
improvements

**Comment by raunak51299** [comment]
Hey, I was pondering if we could remove the newlines from the output we could save so many tokens.
