### ISSUE TITLE
Bug in MaxFileSize Calculation?

### ISSUE THREAD

**Issue by wwoodsTM** [fargusplumdoodle/dump_dir#3]
Hi,

I got a "FILE TOO LARGE" error for a source file under 1 mb.

I checked the FileProcessor code and noticed that the MaxFileSize calculation uses "10 * 1024 * 10", which if it's in bytes as I believe Go uses for FileInfo, this would be 100 KB instead of the intended 10 MB. If it is meant to be 10 mb I believe the line should be:

const MaxFileSize = 10 * 1024 * 1024 // 10 MB

Just wanted to give you a heads-up! Thank you for your helpful project.

**Comment by fargusplumdoodle** [comment]
This is certainly an inconsistency. I feel like 100 KB is preferable over 10 MB. I think I was fiddling with this and forgot to update the comment.

If it would be preferable, I could update it so you can specify the maximum filesize with a default of 100 KB?

**Comment by wwoodsTM** [comment]
For my use case a 100 KB limit was very unhelpful and blocked the most key files that were needed, so I had to manually paste in some things. So I feel customization would be quite helpful for sure.

**Comment by fargusplumdoodle** [comment]
Ayo I will add that, right now I am just updating the docs to be honest about the file size limit

**Comment by fargusplumdoodle** [comment]
I have added the relevant changes in https://github.com/fargusplumdoodle/dump_dir/pull/4. 

[v1.1.0 has the new changes](https://github.com/fargusplumdoodle/dump_dir/releases/tag/v1.1.0)

If you are on a unix based OS you can simply run this command to install the latest version:
```bash
curl -sfL https://raw.githubusercontent.com/fargusplumdoodle/dump_dir/main/install.sh | bash
```

Now you can add `-m` and set any maximum filesize you want, the docs reflect this change.
