### ISSUE TITLE
Find/Ignore files by glob

### ISSUE THREAD

**Issue by fargusplumdoodle** [fargusplumdoodle/dump_dir#5]
Should have a `--glob` or `-g` option to specify patterns to find files with

**Comment by Meandmybadself** [comment]
[Took a stab at implementing that here.](https://github.com/fargusplumdoodle/dump_dir/pull/14)

**Comment by fargusplumdoodle** [comment]
Thank you so much for contributing! 

Can I ask, how long have you been using `dump_dir` ? Where did you hear about it? I only made one post on Reddit when I first started this.

Do you have any other pain points or things you wish it had? 

For the record I am dramatically improving the test framework and adding a config file in https://github.com/fargusplumdoodle/dump_dir/pull/13
